:: Posiciona en la carpeta actual...
:: LLama a GCC || archivos .c || -output nombreDelEjecutable
:: Abre el ejecutable...
:: Pausa el script...

:: %cd%
gcc cliente.c socket_utils.c -o cliente -lws2_32
.\cliente
:: pause
